### ISSUE TITLE
async is not available?

### ISSUE THREAD

**Issue by mdeora** [extractr-io/rialto#2]
No async communication ?

**Comment by nesk** [comment]
Nope, if you want to create a bridge which will start long running actions then you should use your bridge in some queues, not in your main PHP process.

**Comment by mdeora** [comment]
Ok, but even for short running parallel tasks might have been helpful. eg. fetching html of multiple urls and firing response event as it gets the response to a async handler in PHP.

**Comment by nesk** [comment]
Actually, parallel requests could be a great idea, I will think about a solution and see if it can be easily implemented, either in Rialto or PuPHPeteer.
